version: "3"

tasks:
  build:
    cmds:
      - go build -o app server/cmd/server/main.go

  test:
    cmds:
      - cd server && env $(cat "../.test.env" | xargs) go test -v ./...

  lint:
    cmds:
      - cd server && golangci-lint run

  run:
    cmds:
      - docker-compose up --build